---
Title: "Projects"
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Machine Learning:

### R:

#### HW1 - Validattion Set, Predicting salaries
[Description](ml_homework_1.html)  
[Solution](kristof_menyhert_machinelearnig_hw1.html)

#### HW2 - Classification Problem, Predict no-show rate
[Description](ml_homework_2.html)  
[Solution](kristof_menyhert_machinelearnig_hw2.html)

#### HW3 - Clustering, PCA
[Description](ml_homework_3.html)  
[Solution](kristof_menyhert_machinelearnig_hw3.html)

#### HW4 - Random Forest, Boosting, XBoost
[Description](ml_homework_4.html)  
[Solution](kristof_menyhert_machinelearnig_II_hw1.html)

#### HW5 - H2O, Deep Learning, Stacking
[Description](ml_homework_5.html)  
[Solution](kristof_menyhert_machinelearnig_II_hw2.html)

#### Deep learning in R: MNIST example
In this exercise I used a NN model in order to classify handwritten numbers.  
[solution](mnist_example_q1.html)

#### Deep learning in R: classifying IMDB reviews
In this example I used a NN model to classify IMDB reviews into two categories (positive/negative)  
[Solution](imdb_example_q2.html) 

#### Deep learning in R: Homework  
In this project our task was to enter to a Kaggle competition with a deep learning model. I choose the [Santander challenge](https://www.kaggle.com/c/santander-value-prediction-challenge). I was able to make a working deep learning model, but the problem what I examined was not realy suitable for deep learning. Therefore the prediction power was relatively low. After experimenting a while with deep learning models I decided to run a XGBoost model which set me to the top 1/3 of the leadboard.  
[script can be find here](santander_deep_learning.html)

### Python:

#### 1st Project
In this project I got a data about a marketing campaign of a bank to analyze it. [More information](http://archive.ics.uci.edu/ml/index.php)   
[Solution](data_beadando_menyhert_kristof.html)

### Data Analysis:

#### HW2 - Predicting bankrupcy rates
[Description](DA4_Assignment2.pptx)  
[Solution](menyhert_kristof_da4_hw2.html)

### Other:

[A Dashboard what I made for a competition](https://krinya.shinyapps.io/OTP_verseny/)  
[Crypto example](jo_crypto_v1.html)  
[Marahon example plot](/marathon/marathon.html)